<?php

namespace wbrowar\adminbar\helpers;

use Craft;
use craft\helpers\App;
use craft\helpers\Json;
use wbrowar\adminbar\AdminBar;
use wbrowar\adminbar\web\assets\AdminBarAssetCss;
use wbrowar\adminbar\web\assets\AdminBarAssetJs;

class AdminBarAsset
{
    /**
     * When in local development mode, register the Vite dev server.
     * Otherwise, register the asset bundles.
     *
     * @param bool $useCss Registers CSS stylesheet asset bundle.
     * @param bool $useJs Registers JavaScript asset bundle.
     * @return void
     * @throws \yii\base\InvalidConfigException
     */
    public static function registerAssetFiles(bool $useCss = false, bool $useJs = false): void
    {
        if (App::parseEnv('$VITE_ADMIN_BAR_HMR')) {
            Craft::$app->getView()->registerJsFile('http://localhost:3300/admin-bar.ts', ['defer' => true, 'type' => 'module']);
        } else {
            if ($useCss) {
                Craft::$app->getView()->registerAssetBundle(AdminBarAssetCss::class);
            }
            if ($useJs) {
                Craft::$app->getView()->registerAssetBundle(AdminBarAssetJs::class);
            }
        }
    }

    /**
     * Get paths of all JS and CSS files generated by Vite
     *
     * @param string $filename The name of the Vite entry file, usually 'main.ts'
     * @return array
     */
    public static function getPathsToAssetFiles(string $filename): array
    {
        $assetPaths = [
            'css' => [
                'filename' => '',
                'path' => '',
            ],
            'js' => [
                'filename' => '',
                'path' => '',
            ],
        ];

        $manifestPath = AdminBar::$plugin->getBasePath() . '/web/assets/dist/.vite/manifest.json';

        if (file_exists($manifestPath)) {
            $manifestJson = file_get_contents($manifestPath);

            if (!empty($manifestJson)) {
                $manifest = Json::decodeIfJson($manifestJson);

                if (!empty($manifest) && $manifest[$filename]) {
                    $path = Craft::$app->getAssetManager()->getPublishedUrl('@wbrowar/adminbar/web/assets/dist/', true);

                    if (!empty($path)) {
                        if ($manifest[$filename]['css'] ?? false) {
                            $assetPaths['css']['filename'] = substr($manifest[$filename]['css'][0], 7);
                            $assetPaths['css']['path'] = $path . '/' . $manifest[$filename]['css'][0];
                        }
                        if ($manifest[$filename]['file'] ?? false) {
                            $assetPaths['js']['filename'] = substr($manifest[$filename]['file'], 7);
                            $assetPaths['js']['path'] = $path . '/' . $manifest[$filename]['file'];
                        }
                    }
                }
            }
        }

        return $assetPaths;
    }
}